# Define the source files
PYTHON_FILES = main.py open_ide.py tool_details.py remove_permanent_files.py remove_javasoft_key.py main_window.py find_tool_executable.py

# Define the command to use for macOS
PYINSTALLER_MACOS = pyinstaller

# Define the path to CrossOver's Wine
CROSSOVER_WINE = /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/bin/wine

# Define the path to the PyInstaller script in the CrossOver environment
PYINSTALLER_WINDOWS = "C:/users/crossover/AppData/Local/Programs/Python/Python312/Scripts/pyinstaller.exe"

# Define the path to your CrossOver bottle (escape spaces)
WINEPREFIX = "/Users/michalprikryl/Library/Application\ Support/CrossOver/Bottles/Compiler"

# Target for macOS executable
macOS: main_macOS

main_macOS: $(PYTHON_FILES)
	$(PYINSTALLER_MACOS) --onefile --windowed --name main_macOS main.py

# Target for Windows executable using CrossOver's Wine
windows: main.exe

main.exe: $(PYTHON_FILES)
	WINEPREFIX=$(WINEPREFIX) $(CROSSOVER_WINE) $(PYINSTALLER_WINDOWS) --onefile --windowed --name main.exe --hidden-import=PyQt5 main.py

# Clean up the build files and directories generated by PyInstaller
clean:
	rm -rf build/ dist/ __pycache__/ *.spec main.exe main_macOS

.PHONY: all clean macOS windows
